### ISSUE TITLE
Weapon dissapear in cars

### ISSUE THREAD

**Issue by zZOGZz** [Demigod916/ox_inventory_addons#1]
The weapons are dissapearing when you enter and exit a vehicle.
This does not happen with all weapons, in this case it only happened with the "WEAPON_SNIPERRIFLE'.
Please watch the video to notice.
https://streamable.com/pag2ho

**Comment by Demigod916** [comment]
@zZOGZz is it possible that its not weapon specific, but just always the 2nd slot weapon?

**Comment by Demigod916** [comment]
this ism now fixed in v1.1.3 https://github.com/Demigod916/ox_inventory_addons/releases/tag/v1.1.3
