### ISSUE TITLE
New update crashes poeple if they equip gold on their weapons

### ISSUE THREAD

**Issue by riNdes** [Demigod916/ox_inventory_addons#2]
Hello, the new update cause instant crash for players if they have weapons with 'at_skin_luxe', after that i removed the tint from the weapon by the Database all crashes stopped for players that was having the issue.

**UPDATE:**
I tested it out - and it only happends if you have 'WEAPON_PUMPSHOTGUN' equiped with 'at_skin_luxe' i get instant crash.
So i have 'WEAPON_CARBINERIFLE' equiped with 'at_skin_luxe' there is no problems.

**Comment by Demigod916** [comment]
backItems has been fully rewritten.
