### ISSUE TITLE
Error with new update

### ISSUE THREAD

**Issue by SleepingFox25** [Demigod916/ox_inventory_addons#3]
Hello, 
I got a small problem with the update 1.2.5, when I start the script, I got those errors who arrive on the F8 console :

![image](https://github.com/Demigod916/ox_inventory_addons/assets/127875904/6bfa069a-76e5-4d85-ad47-138dbe8e9b5a)

I don't know how to solve it, if you got a solution, I try to install it without modifying the files, but still got the error

**Comment by Demigod916** [comment]
@SleepingFox25 this is an issue on my end, i will be fixing it today

**Comment by Demigod916** [comment]
@SleepingFox25 should be resolved in v1.2.6
