### ISSUE TITLE
[POSSIBLE-ISSUE] Adhesive Crash

### ISSUE THREAD

**Issue by MrNewb** [Demigod916/ox_inventory_addons#3]
Possible issue, throwing it out there and am ok with it being unrelated but on 2802+ this causes an adhesive crash. Troubleshooting steps, connect in with multiple players and crash.
Disable script connect in, no crash.
I have been able to reproduce this every time with 10+ players. Im open to the idea its unrelated but this seems to be the cause as its the only change.

**Comment by Demigod916** [comment]
thats interesting. i developed this on a server using gamebuild 2802. maybe you can try deleting each module 1 at a time and see
if it happens with a specific module

**Comment by Randolio** [comment]
Was also having the adhevise crash error. Narrowed it down to this script and no crashes since removing. Whenever adding it back in, the crashes begin.

**Comment by Randolio** [comment]
I'm on build 2699 btw.

**Comment by Demigod916** [comment]
Is there a specific repro for this or just happens on load?

**Comment by Randolio** [comment]
It was honestly really random for me. It doesn't happen to me when I'm alone. Majority of the time, its like a minute after loading in, other times you can literally go a few hours before you crash. I really think it depends on player count.

**Comment by Demigod916** [comment]
@MrNewb @Randolio what fivem version are you both using? Release/beta/latest?

**Comment by reeeum** [comment]
Can confirm -- We still get the crash using this resource. It believe its something to do with the way it spawns the props.
I've removed the back items and carry props left in the drag craft and all works correctly.

Also something else to note if you use the Durty Cloth Tool you may also get the adhesive Crash.

We're on 2802 currently

**Comment by Randolio** [comment]
@Demigod916 Tested on all 3 versions of fivem, crashed on all.

**Comment by MrNewb** [comment]
I only used back items myself, but 2802 and the newest build.

**Comment by Demigod916** [comment]
Well I'll certainly try and investigate. Maybe someone can grab me a crash log. I cant get it to crash.

**Comment by Demigod916** [comment]
seems to be a lot of adhesive issues going around recently/

**Comment by Randolio** [comment]
Yh, I could never get it to crash by myself. Only happens with multiple players

**Comment by KuMoNDev** [comment]
Im getting adhesive crashes too from items on back.

**Comment by Demigod916** [comment]
> Im getting adhesive crashes too from items on back. 

Yeah it wasnt happening when i first made this 2 months ago. Seems to be that something has changed in fivem since ive made this. Could possibly be related to statebags or possibly how items are created, but im currently unsure

**Comment by YasinY** [comment]
Can confirm. Can't use this, adhesive.dll crash

**Comment by AlHsnn** [comment]
![image](https://github.com/Demigod916/ox_inventory_addons/assets/87451245/8526958d-5b85-4328-97f6-0422664f003c)

**Comment by Demigod916** [comment]
@Flek26 still investigating. if you send me crash logs it could help as well

**Comment by Demigod916** [comment]
solved in v1.0.3
