### ISSUE TITLE
error on login

### ISSUE THREAD

**Issue by IlMicioLetale** [Demigod916/ox_inventory_addons#4]
![Screenshot 2024-01-29 015713](https://github.com/Demigod916/ox_inventory_addons/assets/121300910/55f433ec-a5ce-4e00-8895-ef7e35bd2aa2)
Give me this error, i don't know why
Try to wait to load the function backitems, but same error

**Comment by Demigod916** [comment]
it can load one of your weapons. Try to use one weapon at a time until you see which one is causing error

**Comment by IlMicioLetale** [comment]
All single weapon gave this error
Try Snioee rifle, Carbine rifle ecc
I dont know why i have this problem

**Comment by Demigod916** [comment]
@IlMicioLetale  have you changed the script at all from default?

**Comment by IlMicioLetale** [comment]
The script all stock! Latest ox  lib, Ox inventory 2.36

**Comment by IlMicioLetale** [comment]
It can be the spawn camera in my opinion, right?

**Comment by Demigod916** [comment]
the error comes from it trying to request a weapon asset and failing. not sure how this would be possible if the script is stock and you are using stock weapons

**Comment by Demigod916** [comment]
unable to reproduce
