### ISSUE TITLE
The guns are sticking to my back, when I reverse into the city and there's no way I can get out

### ISSUE THREAD

**Issue by rodrigofueda** [Demigod916/ox_inventory_addons#5]
Weapons and items are sticking to my back when I go to town, how can I fix this?

**Comment by rodrigofueda** [comment]
or when I leave the city the same thing
![image](https://github.com/Demigod916/ox_inventory_addons/assets/158107238/5c7694b0-1e3c-46dd-b1e3-dcce22ee1da1)

**Comment by rodrigofueda** [comment]
![image](https://github.com/Demigod916/ox_inventory_addons/assets/158107238/b927016a-4eed-420c-8e7b-01bfe0b825b7)

**Comment by rodrigofueda** [comment]
![image](https://github.com/Demigod916/ox_inventory_addons/assets/158107238/73837109-1900-4d3d-a1d1-c53b17af03c8)

**Comment by Demigod916** [comment]
unable to reproduce

**Comment by Demigod916** [comment]
Ive been informed that this is likely a server issue due to scripts requesting models and never setting them to no longer needed. Causing the memory to be full for models

**Comment by rodrigofueda** [comment]
What can I do about it?

**Comment by Demigod916** [comment]
In all your scripts whenever a model is requested, after its used to create the entity, then the model needs to be set as no longer needed
