### ISSUE TITLE
Back weapons dissapear when exiting a vehicle

### ISSUE THREAD

**Issue by zZOGZz** [Demigod916/ox_inventory_addons#6]
When you enter in a vehicle and then exit the weapon disappears, if you move any item in ox_inventory they will reappear.

**Comment by Demigod916** [comment]
> When you enter in a vehicle and then exit the weapon disappears, if you move any item in ox_inventory they will reappear.

Ill check this out and get a fix pushed if i can reproduce it

**Comment by Demigod916** [comment]
https://streamable.com/pcccgj
